"""Render a Cotter JSON report as GitHub-flavored Markdown.

Pure and dependency-free. It reads only the stable, versioned JSON schema
a Cotter run emits (``cotter_report_version``), never the ``cotter``
library — so the same renderer works regardless of which ``cotterbot``
version produced the report, and it is trivially unit-testable.

The output is used both for the GitHub Actions job summary and for the
sticky pull-request comment.
"""

from __future__ import annotations

from typing import Any

# The badge shown per category and for the overall verdict.
_STATUS = {True: "✅", False: "❌", None: "➖"}
_VERDICT = {True: "✅ **PASS**", False: "❌ **FAIL**"}

SCHEMA_VERSION = 1


def _cell(text: Any) -> str:
    """Make an arbitrary string safe inside a Markdown table cell."""
    s = str(text)
    return s.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def counts(report: dict) -> tuple[int, int, int]:
    """Return (passing, failing, informational) category counts."""
    results = report.get("results", [])
    n_pass = sum(1 for r in results if r.get("passed") is True)
    n_fail = sum(1 for r in results if r.get("passed") is False)
    n_info = sum(1 for r in results if r.get("passed") is None)
    return n_pass, n_fail, n_info


def marker(tag: str) -> str:
    """The hidden HTML marker that identifies a sticky comment."""
    return f"<!-- cotter-action:{tag} -->"


def to_markdown(
    report: dict,
    *,
    title: str = "Cotter report",
    tag: str | None = None,
    run_url: str | None = None,
) -> str:
    """Render a Cotter report dict as a Markdown block.

    ``tag`` embeds a hidden marker as the first line so a poster can find
    and update its own sticky comment. ``run_url`` links back to the CI
    run in the footer.
    """
    lines: list[str] = []
    if tag is not None:
        lines.append(marker(tag))

    schema = report.get("cotter_report_version")
    policy = report.get("policy_name", "?")
    env = report.get("env_id", "?")
    overall = bool(report.get("overall_passed"))
    n_pass, n_fail, n_info = counts(report)

    lines.append(f"## {title}")
    lines.append("")
    lines.append(
        f"**Policy** `{_cell(policy)}` on `{_cell(env)}` — "
        f"OVERALL: {_VERDICT[overall]}"
    )
    lines.append("")
    lines.append(
        f"`{n_pass}` passing · `{n_fail}` failing · `{n_info}` informational"
    )
    lines.append("")

    results = report.get("results", [])
    if results:
        lines.append("| | Category | Test | Result |")
        lines.append("|:--:|---|---|---|")
        for r in results:
            status = _STATUS.get(r.get("passed"), "➖")
            lines.append(
                f"| {status} | `{_cell(r.get('category', '?'))}` "
                f"| `{_cell(r.get('name', '?'))}` "
                f"| {_cell(r.get('summary', ''))} |"
            )
    else:
        lines.append("_No test categories were executed._")

    manifest = report.get("manifest")
    if manifest:
        lines.append("")
        lines.append("<details><summary>Reproducibility manifest</summary>")
        lines.append("")
        lines.append("| Field | Value |")
        lines.append("|---|---|")
        for key, value in manifest.items():
            if isinstance(value, dict):
                value = ", ".join(f"{k} {v}" for k, v in value.items())
            lines.append(f"| `{_cell(key)}` | {_cell(value)} |")
        lines.append("")
        lines.append("</details>")

    lines.append("")
    footer = "<sub>🛡️ Generated by "
    footer += "[cotter-action](https://github.com/yih0nk/cotter-action)"
    if isinstance(schema, int):
        footer += f" · report schema v{schema}"
    content_hash = report.get("content_sha256")
    if content_hash:
        footer += f" · <code>{_cell(content_hash)}</code>"
    if run_url:
        footer += f" · [workflow run]({run_url})"
    footer += "</sub>"
    lines.append(footer)

    return "\n".join(lines) + "\n"
